<?php

/**
 * @file
 * Provides a stream wrapper and formatters appropriate for accessing and
 * displaying Politiek24 videos.
 */

// Load all Politiek24 file formatters.
require_once dirname(__FILE__) . '/includes/media_politiek24.formatters.inc';

/**
 * Implements hook_media_internet_providers().
 */
function media_politiek24_media_internet_providers() {
  return array(
    'MediaInternetPolitiek24Handler' => array(
      'title' => t('Politiek24'),
    ),
  );
}

/**
 * Implements hook_stream_wrappers().
 */
function media_politiek24_stream_wrappers() {
  return array(
    'politiek24' => array(
      'name' => t('Politiek24 videos'),
      'class' => 'MediaPolitiek24StreamWrapper',
      'description' => t('Remote videos hosted on the Politiek24 video-sharing website.'),
      'type' => STREAM_WRAPPERS_READ_VISIBLE,
    ),
  );
}

/**
 * Implements hook_theme().
 */
function media_politiek24_theme($existing, $type, $theme, $path) {
  return array(
    'media_politiek24_video' => array(
      'variables' => array('uri' => NULL, 'options' => array()),
      'file' => 'media_politiek24.theme.inc',
      'path' => $path . '/themes',
      'template' => 'media-politiek24-video',
    ),
  );
}

/**
 * Implements hook_media_parse().
 *
 * @todo This hook should be deprecated. Refactor Media module to not call it
 *   any more, since media_internet should be able to automatically route to the
 *   appropriate handler. 
 */
function media_politiek24_media_parse($embed_code) {
  $handler = new MediaInternetPolitiek24Handler($embed_code);
  return $handler->parse($embed_code);
}

 /**
 * Implements hook_file_mimetype_mapping_alter().
 */
function media_politiek24_file_mimetype_mapping_alter(&$mapping) {
  $mapping['mimetypes'][] = 'video/politiek24';
}

/**
 * Implements hook_ctools_plugin_api().
 */
function media_politiek24_ctools_plugin_api($module, $api) {
  if ($module == 'file_entity' && $api == 'file_default_displays') {
    return array('version' => 1);
  }
}
